- name: Deploy Docker container on worker node
  hosts: worker
  become: true

  vars:
    app_dir: /home/ubuntu/app

  tasks:

    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory

    - name: Copy project files
      copy:
        src: "{{ playbook_dir }}/../"
        dest: "{{ app_dir }}"

    - name: Remove old container
      command: docker rm -f zomato-container
      ignore_errors: yes

    - name: Remove old image
      command: docker rmi zomato-app
      ignore_errors: yes

    - name: Build Docker image
      command: docker build -t zomato-app .
      args:
        chdir: "{{ app_dir }}"

    - name: Run container
      command: docker run -d -p 8080:8080 --name zomato-container zomato-app
